// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXOnbZwqgsuMF3TFiwybdaRuWrNfWjNqM',
    appId: '1:866487395467:web:a057f12cfb6a6370dca08e',
    messagingSenderId: '866487395467',
    projectId: 'flutter-full-e50a1',
    authDomain: 'flutter-full-e50a1.firebaseapp.com',
    storageBucket: 'flutter-full-e50a1.appspot.com',
    measurementId: 'G-9D6KQ2PYYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtphqKHzqhBzSTPzAC7kOeYOsertDRczw',
    appId: '1:866487395467:android:f70f2f5a856274e4dca08e',
    messagingSenderId: '866487395467',
    projectId: 'flutter-full-e50a1',
    storageBucket: 'flutter-full-e50a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAD3OhR-TC4WS6ypdhqaTvY7uJAEWlZw',
    appId: '1:866487395467:ios:2711e685183c4cd9dca08e',
    messagingSenderId: '866487395467',
    projectId: 'flutter-full-e50a1',
    storageBucket: 'flutter-full-e50a1.appspot.com',
    iosClientId: '866487395467-fs341qobicir3nadv4qkqrflc5omjjjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFullApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAD3OhR-TC4WS6ypdhqaTvY7uJAEWlZw',
    appId: '1:866487395467:ios:2711e685183c4cd9dca08e',
    messagingSenderId: '866487395467',
    projectId: 'flutter-full-e50a1',
    storageBucket: 'flutter-full-e50a1.appspot.com',
    iosClientId: '866487395467-fs341qobicir3nadv4qkqrflc5omjjjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFullApp',
  );
}
